services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8081
        - VITE_FRONTEND_PORT=8080
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DOMAIN=http://localhost:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
